// Copyright 2012 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef SYZYGY_PE_UNITTEST_UTIL_H_
#define SYZYGY_PE_UNITTEST_UTIL_H_

#include <windows.h>

#include "base/file_path.h"
#include "base/file_util.h"
#include "gtest/gtest.h"
#include "syzygy/common/unittest_util.h"

namespace testing {

class PELibUnitTest : public testing::ApplicationTestBase {
 public:
  // Name of the test DLL and PDB.
  static const wchar_t kDllName[];
  static const wchar_t kDllPdbName[];

  // Name of the various test DLLs generated by the test_data project.
  // These are placed in $(OutputDir)\test_data, so use
  // GetExeTestDataRelativePath to build paths to them.
  static const wchar_t kRandomizedTestDllName[];
  static const wchar_t kRandomizedTestDllPdbName[];
  static const wchar_t kRpcInstrumentedDllName[];
  static const wchar_t kRpcInstrumentedDllPdbName[];

  // Performs a series of assertations on the test DLL's integrity.
  static void CheckTestDll(const FilePath& path);
};

}  // namespace testing

#endif  // SYZYGY_PE_UNITTEST_UTIL_H_
