// Copyright 2012 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef SYZYGY_PE_UNITTEST_UTIL_H_
#define SYZYGY_PE_UNITTEST_UTIL_H_

#include <windows.h>

#include "base/file_util.h"
#include "base/files/file_path.h"
#include "gtest/gtest.h"
#include "syzygy/block_graph/block_graph.h"
#include "syzygy/block_graph/orderer.h"
#include "syzygy/block_graph/unittest_util.h"
#include "syzygy/common/unittest_util.h"
#include "syzygy/core/unittest_util.h"
#include "syzygy/pe/coff_file.h"
#include "syzygy/pe/image_layout.h"
#include "syzygy/pe/pe_file.h"

namespace testing {

// Name of the test DLLs and PDBs. These exist in the output directory, and
// again in the test_data directory.
extern const wchar_t kTestDllName[];
extern const wchar_t kTestDllPdbName[];
extern const wchar_t kTestDllName64[];
extern const wchar_t kTestDllPdbName64[];

// Name of the integrations tests DLLs and PDBs.
extern const wchar_t kIntegrationTestsDllName[];
extern const wchar_t kIntegrationTestsDllPdbName[];

// Name of the DLL containing an empty exports directory.
extern const wchar_t kNoExportsDllName[];
extern const wchar_t kNoExportsDllPdbName[];

// Name of the test DLL object files and the PDB files where their type
// information has been emitted, relative to the test_data directory.
// The two object files are guaranteed to be in the specified format.
extern const wchar_t kTestDllCoffObjName[];
extern const wchar_t kTestDllLtcgObjName[];
extern const wchar_t kTestDllCoffObjPdbName[];
extern const wchar_t kTestDllLtcgObjPdbName[];

// Statically checked in object files that explore some of the boundary cases
// of COFF files. These are also relative to the test data directory. These live
// in syzygy\pe\test_data, thus should be referred to using GetSrcRelativePath.
extern const wchar_t kMachineTypeNullCoffName[];

// Name of the various test DLLs generated by the test_data project.
// These are placed in $(OutputDir)\test_data, so use
// GetExeTestDataRelativePath to build paths to them.
extern const wchar_t kAsanInstrumentedTestDllName[];
extern const wchar_t kAsanInstrumentedTestDllPdbName[];
extern const wchar_t kBBEntryInstrumentedTestDllName[];
extern const wchar_t kBBEntryInstrumentedTestDllPdbName[];
extern const wchar_t kCallTraceInstrumentedTestDllName[];
extern const wchar_t kCallTraceInstrumentedTestDllPdbName[];
extern const wchar_t kCoverageInstrumentedTestDllName[];
extern const wchar_t kCoverageInstrumentedTestDllPdbName[];
extern const wchar_t kProfileInstrumentedTestDllName[];
extern const wchar_t kProfileInstrumentedTestDllPdbName[];
extern const wchar_t kRandomizedTestDllName[];
extern const wchar_t kRandomizedTestDllPdbName[];

// Name of the various trace files.
extern const wchar_t *kBBEntryTraceFiles[4];
extern const wchar_t *kBranchTraceFiles[4];
extern const wchar_t *kCallTraceTraceFiles[4];
extern const wchar_t *kCoverageTraceFiles[4];
extern const wchar_t *kProfileTraceFiles[4];

// This class wraps an HMODULE and ensures that ::FreeLibrary is called when it
// goes out of scope.
class ScopedHMODULE {
 public:
  ScopedHMODULE();
  explicit ScopedHMODULE(HMODULE v);
  ~ScopedHMODULE();

  void Reset(HMODULE v);
  void Release();

  operator HMODULE() const {
    return value_;
  }

 private:
  HMODULE value_;
};

// Given a block-graph that represents a decomposed PE image this reaches in
// and modifies the GUID and path values in place. This prevents any written
// images from matching the same symbol file. If this is not done it is possible
// for the debugger to cause an exception to be raised while loading a symbol
// file whose signature does match, but whose contents don't match, a
// transformed PE file.
// @param dos_header_block The DOS header block.
// @note Meant to be called from within an ASSERT_NO_FATAL_FAILURE block.
void TwiddlePdbGuidAndPath(block_graph::BlockGraph::Block* dos_header_block);

class PELibUnitTest : public testing::ApplicationTestBase {
 public:
  // Decomposes test_dll, populating the given PE file and image layout.
  static void DecomposeTestDll(pe::PEFile* pe_file,
                               pe::ImageLayout* image_layout);

  // Performs a series of assertions on the test DLL's integrity.
  static void CheckTestDll(const base::FilePath& path);

  // Loads the test DLL and returns its module handle.
  static void LoadTestDll(const base::FilePath& path, ScopedHMODULE* module);
};

class CoffUnitTest : public testing::PELibUnitTest {
 public:
  CoffUnitTest() : image_layout_(&block_graph_) {
  }

  virtual void SetUp() OVERRIDE;

  // Decompose test_dll.coff_obj.
  void DecomposeOriginal();

  // Reorder and lay out test_dll.coff_obj into a new object file, located
  // at new_test_dll_obj_path_.
  void LayoutAndWriteNew(block_graph::BlockGraphOrdererInterface* orderer);

  // Writes and redecomposes the COFF file, and ensures that all symbols have
  // made it through the process.
  void TestRoundTrip();

  base::FilePath test_dll_obj_path_;
  base::FilePath new_test_dll_obj_path_;
  base::FilePath temp_dir_path_;

  // Original image details.
  testing::DummyTransformPolicy policy_;
  pe::CoffFile image_file_;
  block_graph::BlockGraph block_graph_;
  pe::ImageLayout image_layout_;
  block_graph::BlockGraph::Block* headers_block_;
};

}  // namespace testing

#endif  // SYZYGY_PE_UNITTEST_UTIL_H_
